name: Add linked service

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."

jobs:
   create-linked-service:
    name: Create linked service for Azure synapse pipeline to use Azure Key Vault for Az Func
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: "dev"
    env:
      NO_PROXY: .file.core.windows.net,.vault.azure.net,.blob.core.windows.net,.dfs.core.windows.net,.dev.azuresynapse.net,.sql.azuresynapse.net,registry.npmjs.org,www.powershellgallery.com

    steps:
      # Step 1: Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Step 2: Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

     # Step 3: Create Linked Service to Key Vault Secret
      - name: Create Linked Service
        shell: bash
        run: |
                # Define variables
                RESOURCE_GROUP_NAME="lineagempg"
                SYNAPSE_WORKSPACE_NAME="lineagempg" # Replace with your Synapse workspace name
                KEY_VAULT_NAME="testfunckeyvault1"
                KEY_VAULT_SECRET_NAME="testfunckeyvaultgit1" # Replace with your Key Vault secret name
                LINKED_SERVICE_NAME="funclinkkeyvaultgit" # Replace with the desired linked service name
                
                # Debug Azure CLI
                echo "Checking Azure account..."
                az account show
                
                # Retrieve Key Vault secret value
                echo "Retrieving Key Vault secret value..."
                KEY_VAULT_SECRET_VALUE=$(az keyvault secret show --vault-name "$KEY_VAULT_NAME" --name "$KEY_VAULT_SECRET_NAME" --query "value" -o tsv)
                
                if [ -z "$KEY_VAULT_SECRET_VALUE" ]; then
                  echo "Error: Secret '$KEY_VAULT_SECRET_NAME' not found in Key Vault '$KEY_VAULT_NAME'."
                  exit 1
                fi
                
                # Retrieve Key Vault base URL
                echo "Retrieving Key Vault base URL..."
                KEY_VAULT_BASE_URL="https://$KEY_VAULT_NAME.vault.azure.net/"
                
                # Create Linked Service JSON file
                cat <<EOF > linkedservice.json
                {
                  "properties": {
                    "type": "AzureKeyVault",
                    "typeProperties": {
                      "baseUrl": "$KEY_VAULT_BASE_URL",
                      "secretName": "$KEY_VAULT_SECRET_NAME",
                      "secretValue": "$KEY_VAULT_SECRET_VALUE"
                    }
                  }
                }
                EOF
                
                # Create Linked Service in Azure Synapse
                echo "Creating Linked Service in Azure Synapse..."
                az synapse linked-service create \
                  --workspace-name "$SYNAPSE_WORKSPACE_NAME" \
                  --name "$LINKED_SERVICE_NAME" \
                  --file linkedservice.json
                
                echo "Linked Service has been successfully created."
