name: Add Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."

jobs:
  exec:
    name: Add Azure Function Key to Azure Key Vault
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: "dev"
    env:
      NO_PROXY: .file.core.windows.net,.vault.azure.net,.blob.core.windows.net,.dfs.core.windows.net,.dev.azuresynapse.net,.sql.azuresynapse.net,registry.npmjs.org,www.powershellgallery.com

    steps:
      # Step 1: Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Step 2: Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Retrieve Function Key and Add to Key Vault
      - name: Add Azure Function Key to Key Vault
        shell: bash
        run: |
          # Define variables
          RESOURCE_GROUP_NAME="lineagempg"
          FUNCTION_APP_NAME="testfunc"
          KEY_VAULT_NAME="testfungithub"
          SECRET_NAME="testfunckeyvault" # Name of the secret in Key Vault

          # Debug Azure CLI
          echo "Checking Azure account..."
          az account show

          echo "Retrieving Azure Function key..."
          FUNCTION_KEY=$(az functionapp keys list --resource-group "$RESOURCE_GROUP_NAME" --name "$FUNCTION_APP_NAME" --query "functionKeys.default" -o tsv)

          echo "Adding Azure Function key to Key Vault..."
          az keyvault secret set --vault-name "$KEY_VAULT_NAME" --name "$SECRET_NAME" --value "$FUNCTION_KEY"

          echo "Azure Function key has been successfully added to Key Vault."

      # Step 4: Logout from Azure
      - name: Azure Logout
        shell: pwsh
        run: |
          Disconnect-AzAccount
