name: add secrets
on:
      
   workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."        

jobs:
  exec:
    name: Add Az Func key to Azure Key Vault
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: "dev"
    env:
      NO_PROXY: .file.core.windows.net,.vault.azure.net,.blob.core.windows.net,.dfs.core.windows.net,.dev.azuresynapse.net,.sql.azuresynapse.net,registry.npmjs.org,www.powershellgallery.com
    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4
   # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      # Step 3: Run PowerShell Script to Add Function Key to Key Vault
      - name: Add Azure Function Key to Key Vault
        shell: pwsh
        run: |
          # Define variables
          $resourceGroupName = lineagempg
          $functionAppName = testfunc
          $keyVaultName = testfungithub
          $secretName = testfunckeyvault # Name of the secret in Key Vault

          # Step 1: Retrieve the Azure Function key using the Service Principal
          $functionKeys = Get-AzFunctionAppKey -ResourceGroupName $resourceGroupName -Name $functionAppName
          $defaultKey = $functionKeys.FunctionKeys["default"] # Retrieve the default function key

          # Step 2: Add the Azure Function key to Azure Key Vault
          Set-AzKeyVaultSecret -VaultName $keyVaultName -Name $secretName -SecretValue $defaultKey

          Write-Output "Azure Function key has been successfully added to Key Vault."

      # Step 4: Logout from Azure
      - name: Azure Logout
        shell: pwsh
        run: |
          Disconnect-AzAccount
