name: deploy Template check

on:
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."    

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Template Deploy
    environment: ${{ inputs.environment }}
    continue-on-error: false

    steps:
      # Step 1: Check out the repository
      - name: Check Out Repository
        uses: actions/checkout@v4

      # Step 2: Azure Login
      - name: Azure Login
        id: azure_login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set the Azure subscription
      #- name: Set Azure Subscription
      #  run: |
      #    az account set --subscription "${{ secrets.subscriptionId }}"


      # Deploy the Synapse template
      - name: Azure Deploy
        uses: azure/arm-deploy@v1
        with: 
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: 'lineagempguk'
          template: 'config/keyvaulttemp.json'
          parameters: 'config/keyvaultparameter.json'           
          deploymentName: 'synapsedeploykv'
  
