name: Create Container, Upload Config File
on:
  workflow_dispatch:

jobs:
  exec:
    name: Create Container, Upload Config File
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: "dev"
    env:
      NO_PROXY: .file.core.windows.net,.vault.azure.net,.blob.core.windows.net,.dfs.core.windows.net,.dev.azuresynapse.net,.sql.azuresynapse.net,registry.npmjs.org,www.powershellgallery.com

    steps:
      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Show proxy settings in ENV
      - name: Show proxy settings in ENV
        run: |
          echo $HTTP_PROXY
          echo $HTTPS_PROXY
          echo $NO_PROXY

      # Create Container and Upload CSV using Azure CLI
      - name: Create Container and Upload CSV
        shell: bash
        run: |
          # Define variables
          storageAccountName="testpostteamsstores"
          containerName="configfiles"
          filePath="config/configUrl.csv"
          blobName="configUrl.csv"

          # Get storage account key
          storageAccountKey=$(az storage account keys list --account-name $storageAccountName --query "[0].value" -o tsv)

          # Create the container if it doesn't exist
          az storage container create --name $containerName --account-name $storageAccountName --account-key $storageAccountKey

          # Upload the CSV file
          az storage blob upload --account-name $storageAccountName --account-key $storageAccountKey --container-name $containerName --name $blobName --file $filePath

          echo "CSV file uploaded successfully to Azure Storage!"
