name: Alert Function Deployment
on:
 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      function_directory:
        required: true
        type: string
        default: "funcDeployment1"
        description: "Specifies the directory of the Azure Function."
      function_name:
        required: true
        default: "testpostteamsgitGrimGit"
        type: string        
        description: "Name of the function"
      function_rgp:
        required: true
        default: "lineagempguk"
        type: string
        description: "RGP of the function"
      app_settings:
        required: true
        default: "false"
        type: string
        description: "App Settings to be Performed True/False"

jobs:
   deploy:
    runs-on: ubuntu-latest
    name: Function App Deploys
    environment: ${{ inputs.environment }}
    continue-on-error: false
    outputs:
      environment: ${{ steps.set-output-defaults.outputs.environment }}
      function_directory: ${{ steps.set-output-defaults.outputs.function_directory }}
      function_name: ${{ steps.set-output-defaults.outputs.function_name }}
      function_rgp: ${{ steps.set-output-defaults.outputs.function_rgp }}
      app_settings: ${{ steps.set-output-defaults.outputs.app_settings }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |    
          # If workflow_dispatch, use inputs (left), if other trigger, use default env (right)
          echo "environment=${{ inputs.environment || 'dev' }}" >> $GITHUB_OUTPUT
          echo "function_directory=${{ inputs.function_directory || 'function/funcDeployment1' }}" >> $GITHUB_OUTPUT
          echo "function_name=${{ inputs.function_name || 'testpostteamsgitGrimGit' }}" >> $GITHUB_OUTPUT
          echo "function_rgp=${{ inputs.function_rgp || 'lineagempguk' }}" >> $GITHUB_OUTPUT
          echo "app_settings=${{ inputs.app_settings || 'false' }}" >> $GITHUB_OUTPUT
    
   function_deploy:
    needs: [deploy]
    uses: ./.github/workflows/_grimfuncTemplate.yml
    name: "Function App Deploy"
    with:
       environment:  ${{needs.deploy.outputs.environment}}
       function_directory:  ${{needs.deploy.outputs.function_directory}}
       function_name: ${{needs.deploy.outputs.function_name}}
       function_rgp: ${{needs.deploy.outputs.function_rgp}}
       app_settings: ${{needs.deploy.outputs.app_settings}}       
    secrets: inherit


